package net.anware.tmc.colourscroller.scrollables;


import net.minecraft.item.Items;

import static net.anware.tmc.colourscroller.ScrollableHelper.addSet;


public class ColourScrollables {
    public static void init() {
        addSet("colour", Items.WHITE_WOOL, Items.LIGHT_GRAY_WOOL, Items.GRAY_WOOL, Items.BLACK_WOOL,
                Items.RED_WOOL, Items.BROWN_WOOL, Items.ORANGE_WOOL, Items.YELLOW_WOOL,
                Items.LIME_WOOL, Items.GREEN_WOOL, Items.CYAN_WOOL, Items.LIGHT_BLUE_WOOL,
                Items.BLUE_WOOL, Items.PINK_WOOL, Items.MAGENTA_WOOL, Items.PURPLE_WOOL);

        addSet("colour", Items.WHITE_CONCRETE, Items.LIGHT_GRAY_CONCRETE, Items.GRAY_CONCRETE, Items.BLACK_CONCRETE,
                Items.RED_CONCRETE, Items.BROWN_CONCRETE, Items.ORANGE_CONCRETE, Items.YELLOW_CONCRETE,
                Items.LIME_CONCRETE, Items.GREEN_CONCRETE, Items.CYAN_CONCRETE, Items.LIGHT_BLUE_CONCRETE,
                Items.BLUE_CONCRETE, Items.PINK_CONCRETE, Items.MAGENTA_CONCRETE, Items.PURPLE_CONCRETE);

        addSet("colour", Items.WHITE_CONCRETE_POWDER, Items.LIGHT_GRAY_CONCRETE_POWDER, Items.GRAY_CONCRETE_POWDER, Items.BLACK_CONCRETE_POWDER,
                Items.RED_CONCRETE_POWDER, Items.BROWN_CONCRETE_POWDER, Items.ORANGE_CONCRETE_POWDER, Items.YELLOW_CONCRETE_POWDER,
                Items.LIME_CONCRETE_POWDER, Items.GREEN_CONCRETE_POWDER, Items.CYAN_CONCRETE_POWDER, Items.LIGHT_BLUE_CONCRETE_POWDER,
                Items.BLUE_CONCRETE_POWDER, Items.PINK_CONCRETE_POWDER, Items.MAGENTA_CONCRETE_POWDER, Items.PURPLE_CONCRETE_POWDER);

        addSet("colour", Items.WHITE_TERRACOTTA, Items.LIGHT_GRAY_TERRACOTTA, Items.GRAY_TERRACOTTA, Items.BLACK_TERRACOTTA,
                Items.RED_TERRACOTTA, Items.BROWN_TERRACOTTA, Items.ORANGE_TERRACOTTA, Items.YELLOW_TERRACOTTA,
                Items.LIME_TERRACOTTA, Items.GREEN_TERRACOTTA, Items.CYAN_TERRACOTTA, Items.LIGHT_BLUE_TERRACOTTA,
                Items.BLUE_TERRACOTTA, Items.PINK_TERRACOTTA, Items.MAGENTA_TERRACOTTA, Items.PURPLE_TERRACOTTA);

        addSet("colour", Items.WHITE_GLAZED_TERRACOTTA, Items.LIGHT_GRAY_GLAZED_TERRACOTTA, Items.GRAY_GLAZED_TERRACOTTA, Items.BLACK_GLAZED_TERRACOTTA,
                Items.RED_GLAZED_TERRACOTTA, Items.BROWN_GLAZED_TERRACOTTA, Items.ORANGE_GLAZED_TERRACOTTA, Items.YELLOW_GLAZED_TERRACOTTA,
                Items.LIME_GLAZED_TERRACOTTA, Items.GREEN_GLAZED_TERRACOTTA, Items.CYAN_GLAZED_TERRACOTTA, Items.LIGHT_BLUE_GLAZED_TERRACOTTA,
                Items.BLUE_GLAZED_TERRACOTTA, Items.PINK_GLAZED_TERRACOTTA, Items.MAGENTA_GLAZED_TERRACOTTA, Items.PURPLE_GLAZED_TERRACOTTA);

        addSet("colour", Items.WHITE_STAINED_GLASS, Items.LIGHT_GRAY_STAINED_GLASS, Items.GRAY_STAINED_GLASS, Items.BLACK_STAINED_GLASS,
                Items.RED_STAINED_GLASS, Items.BROWN_STAINED_GLASS, Items.ORANGE_STAINED_GLASS, Items.YELLOW_STAINED_GLASS,
                Items.LIME_STAINED_GLASS, Items.GREEN_STAINED_GLASS, Items.CYAN_STAINED_GLASS, Items.LIGHT_BLUE_STAINED_GLASS,
                Items.BLUE_STAINED_GLASS, Items.PINK_STAINED_GLASS, Items.MAGENTA_STAINED_GLASS, Items.PURPLE_STAINED_GLASS);

        addSet("colour", Items.WHITE_STAINED_GLASS_PANE, Items.LIGHT_GRAY_STAINED_GLASS_PANE, Items.GRAY_STAINED_GLASS_PANE, Items.BLACK_STAINED_GLASS_PANE,
                Items.RED_STAINED_GLASS_PANE, Items.BROWN_STAINED_GLASS_PANE, Items.ORANGE_STAINED_GLASS_PANE, Items.YELLOW_STAINED_GLASS_PANE,
                Items.LIME_STAINED_GLASS_PANE, Items.GREEN_STAINED_GLASS_PANE, Items.CYAN_STAINED_GLASS_PANE, Items.LIGHT_BLUE_STAINED_GLASS_PANE,
                Items.BLUE_STAINED_GLASS_PANE, Items.PINK_STAINED_GLASS_PANE, Items.MAGENTA_STAINED_GLASS_PANE, Items.PURPLE_STAINED_GLASS_PANE);

        addSet("colour", Items.WHITE_SHULKER_BOX, Items.LIGHT_GRAY_SHULKER_BOX, Items.GRAY_SHULKER_BOX, Items.BLACK_SHULKER_BOX,
                Items.RED_SHULKER_BOX, Items.BROWN_SHULKER_BOX, Items.ORANGE_SHULKER_BOX, Items.YELLOW_SHULKER_BOX,
                Items.LIME_SHULKER_BOX, Items.GREEN_SHULKER_BOX, Items.CYAN_SHULKER_BOX, Items.LIGHT_BLUE_SHULKER_BOX,
                Items.BLUE_SHULKER_BOX, Items.PINK_SHULKER_BOX, Items.MAGENTA_SHULKER_BOX, Items.PURPLE_SHULKER_BOX);

        addSet("colour", Items.WHITE_CARPET, Items.LIGHT_GRAY_CARPET, Items.GRAY_CARPET, Items.BLACK_CARPET,
                Items.RED_CARPET, Items.BROWN_CARPET, Items.ORANGE_CARPET, Items.YELLOW_CARPET,
                Items.LIME_CARPET, Items.GREEN_CARPET, Items.CYAN_CARPET, Items.LIGHT_BLUE_CARPET,
                Items.BLUE_CARPET, Items.PINK_CARPET, Items.MAGENTA_CARPET, Items.PURPLE_CARPET);

    }
}